language: go
go:
  - '1.12.x'
  - '1.13.x'
go_import_path: 'zgo.at/zpack'
env:
  - 'GO111MODULE=on'
cache:
  directories:
    - '$HOME/.cache/go-build'
    - '$GOPATH/pkg'
notifications:
  email: false
before_cache:
  - 'rm -rf $HOME/.cache/go-build/log.txt $GOPATH/pkg/mod/cache/vcs'
script:
  - 'go vet ./...'
  - 'go generate ./... && [ $(git status -s | wc -l) -gt 1 ] && git status -s && exit 1 || true'
  - 'go test -v -race -coverprofile=coverage.txt -coverpkg=./... ./...'
after_success:
  - 'bash <(curl -s https://codecov.io/bash)'
